Repository AyushSarode/LearningApp, pull requests merged in 2022-10, with the labels that each got.

#4 Added an Anchor Link to Jump to a Specific Section of a Page
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#6 fix: Fix sidebar and add icon in scroll button
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#10 Updated Readme.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#16 Added Preloader
  .vscode/settings.json
  images/small_loader.gif
  index.html
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#22 updated css file
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#30 Updated style.css
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#37 Added css hover effect on buttons
  .vscode/settings.json
  index.html
  style.css
Labels: hacktoberfest-accepted

#40 Created a page to showcase courses
  courses.css
  courses.html
  images/cloud.png
  images/courses-header.jpg
  images/datastructures.png
  images/designprinciples.png
  images/html.png
  images/javascript.png
  images/laptopLearning.png
  images/php.png
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#55 Improved the responsiveness of the course section
  courses.css
Labels: hacktoberfest-accepted

#62 Added hovering effect on the social icons
  style.css
Labels: hacktoberfest-accepted

#60 Feature : Making links on side navbar hover with transition
  style.css
Labels: hacktoberfest-accepted

#72 all the buttons can hover now
  .DS_Store
  images/.DS_Store
  images/Xypo-favi.png
  images/Xypo1.png
  index.html
  style.css
Labels: hacktoberfest-accepted

#71 Designing the mobile view #67
  index.html
  style.css
Labels: hacktoberfest

#73 Designed the Scrollbar
  style.css
Labels: hacktoberfest-accepted

#74 Added appropriate content in the cards of the "courses" section
  courses.html
Labels: hacktoberfest, hacktoberfest-accepted

#81 Add links to the logo for the homepage
  courses.html
  index.html
Labels: hacktoberfest-accepted
